import { ActivityItem, TeacherProfile } from './types';

export const DEFAULT_TEACHER_PROFILE: TeacherProfile = {
  namaGuru: '',
  nip: '',
  nipType: 'NIP',
  jabatan: '',
  namaSekolah: 'SMA NEGERI 03 BOMBANA',
  kelas: '',
  waliKelas: '',
  guruWali: '',
  mataPelajaran: '',
  namaKepalaSekolah: 'Yakob Simson Barthimeus S.Pd., M.Pd., MM',
  nipKepalaSekolah: '19781203200701 1 004',
  jabatanKepalaSekolah: 'Pembina Utama Muda, IV/c',
  kotaTandaTangan: 'Rumbia',
  bebanKerja: '',
  tanggal: '2026-05-20', // Rabu, 20 Mei 2026
};

export const DEFAULT_ACTIVITIES: ActivityItem[] = [
  // 1. Merencanakan Pembelajaran atau Pembimbingan
  {
    id: 'act1_1',
    no: '1',
    component: '1. Merencanakan Pembelajaran atau Pembimbingan',
    activityName: 'Pengkajian kurikulum: Melakukan analisis/penelaahan mendalam kurikulum pembelajaran, kurikulum pembimbingan, atau kurikulum program kebutuhan khusus pada satuan pendidikan.',
    duration: 0,
    timeRange: '',
    isActive: false,
    photos: [],
    photoCaptions: [],
  },
  {
    id: 'act1_2',
    no: '2',
    component: '1. Merencanakan Pembelajaran atau Pembimbingan',
    activityName: 'Pembuatan rencana pelaksanaan (RPP/Modul Ajar): Menyiapkan administrasi, tujuan pembelajaran, metode KBM, serta materi layanan bimbingan/pembimbingan sesuai standar proses.',
    duration: 0,
    timeRange: '',
    isActive: false,
    photos: [],
    photoCaptions: [],
  },

  // 2. Melaksanakan Pembelajaran atau Pembimbingan
  {
    id: 'act2_1',
    no: '3',
    component: '2. Melaksanakan Pembelajaran atau Pembimbingan',
    activityName: 'Melaksanakan Pembelajaran Intrakurikuler (Batas Beban: Paling sedikit 24 jam tatap muka dan paling banyak 40 jam tatap muka per minggu).',
    duration: 0,
    timeRange: '',
    isActive: false,
    photos: [],
    photoCaptions: [],
  },
  {
    id: 'act2_2',
    no: '4',
    component: '2. Melaksanakan Pembelajaran atau Pembimbingan',
    activityName: 'Melaksanakan Layanan Pembimbingan Klasikal / Kelompok Konseling (Bagi Guru BK: Membimbing/mendidik paling sedikit 5 rombongan belajar per tahun).',
    duration: 0,
    timeRange: '',
    isActive: false,
    photos: [],
    photoCaptions: [],
  },
  {
    id: 'act2_3',
    no: '5',
    component: '2. Melaksanakan Pembelajaran atau Pembimbingan',
    activityName: 'Melaksanakan Pembelajaran serta Pendampingan Kokurikuler (termasuk membimbing Projek Penguatan Profil Pelajar Pancasila / P5).',
    duration: 0,
    timeRange: '',
    isActive: false,
    photos: [],
    photoCaptions: [],
  },
  {
    id: 'act2_4',
    no: '6',
    component: '2. Melaksanakan Pembelajaran atau Pembimbingan',
    activityName: 'Melaksanakan Kegiatan Ekstrakurikuler Wajib/Pilihan serta pemberian bimbingan dan layanan konseling psikososial adaptif murid.',
    duration: 0,
    timeRange: '',
    isActive: false,
    photos: [],
    photoCaptions: [],
  },

  // 3. Menilai Hasil Pembelajaran atau Pembimbingan
  {
    id: 'act3_1',
    no: '7',
    component: '3. Menilai Hasil Pembelajaran atau Pembimbingan',
    activityName: 'Melaksanakan rincian penilaian: Melakukan pengolahan hasil ujian (formatif/sumatif), pengkajian capaian kognitif, atau telaah instrumen asesmen BK harian.',
    duration: 0,
    timeRange: '',
    isActive: false,
    photos: [],
    photoCaptions: [],
  },
  {
    id: 'act3_2',
    no: '8',
    component: '3. Menilai Hasil Pembelajaran atau Pembimbingan',
    activityName: 'Melaksanakan tindak lanjut penilaian hasil: Mengerjakan administrasi rekapitulasi nilai, program perbaikan/remedial, dan kelas pengayaan kemandirian murid.',
    duration: 0,
    timeRange: '',
    isActive: false,
    photos: [],
    photoCaptions: [],
  },

  // 4. Membimbing dan Melatih Murid
  {
    id: 'act4_1',
    no: '9',
    component: '4. Membimbing dan Melatih Murid',
    activityName: 'Melaksanakan pembimbingan akademis terstruktur dan pelatihan ketangkasan siswa melalui wadah kokurikuler dan ekstrakurikuler.',
    duration: 0,
    timeRange: '',
    isActive: false,
    photos: [],
    photoCaptions: [],
  },
  {
    id: 'act4_2',
    no: '10',
    component: '4. Membimbing dan Melatih Murid',
    activityName: 'Tugas Guru Wali: Melaksanakan pendampingan akademik personal, pembinaan karakter orisinal, serta soft skills (Ekuivalen 2 Jam Tatap Muka/Minggu).',
    duration: 0,
    timeRange: '',
    isActive: false,
    photos: [],
    photoCaptions: [],
  },

  // 5. Melaksanakan Tugas Tambahan
  {
    id: 'act5_a1',
    no: '11',
    component: '5. Melaksanakan Tugas Tambahan',
    activityName: 'Tugas Utama: Wakil Kepala Satuan Pendidikan (Kesiswaan/Kurikulum/Humas/Sapras) (Ekuivalen 12 Jam Tatap Muka/Minggu).',
    duration: 0,
    timeRange: '',
    isActive: false,
    photos: [],
    photoCaptions: [],
  },
  {
    id: 'act5_a2',
    no: '12',
    component: '5. Melaksanakan Tugas Tambahan',
    activityName: 'Tugas Utama: Ketua Program Keahlian pada Satuan Pendidikan Kejuruan (SMK) (Ekuivalen 12 Jam Tatap Muka/Minggu).',
    duration: 0,
    timeRange: '',
    isActive: false,
    photos: [],
    photoCaptions: [],
  },
  {
    id: 'act5_a3',
    no: '13',
    component: '5. Melaksanakan Tugas Tambahan',
    activityName: 'Tugas Utama: Kepala Perpustakaan Satuan Pendidikan (Ekuivalen 12 Jam Tatap Muka/Minggu).',
    duration: 0,
    timeRange: '',
    isActive: false,
    photos: [],
    photoCaptions: [],
  },
  {
    id: 'act5_a4',
    no: '14',
    component: '5. Melaksanakan Tugas Tambahan',
    activityName: 'Tugas Utama: Kepala Laboratorium, Bengkel, atau Unit Produksi/Teaching Factory (Ekuivalen 12 Jam Tatap Muka/Minggu).',
    duration: 0,
    timeRange: '',
    isActive: false,
    photos: [],
    photoCaptions: [],
  },
  {
    id: 'act5_b1',
    no: '15',
    component: '5. Melaksanakan Tugas Tambahan',
    activityName: 'Tugas Lain: Guru Pembimbing Khusus (GPK) pada Sekolah Penyelenggara Pendidikan Inklusi / Terpadu (Ekuivalen 6 Jam Tatap Muka/Minggu).',
    duration: 0,
    timeRange: '',
    isActive: false,
    photos: [],
    photoCaptions: [],
  },
  {
    id: 'act5_c1',
    no: '16',
    component: '5. Melaksanakan Tugas Tambahan',
    activityName: 'Tugas Lainnya - Wali Kelas: Mengelola administrasi, kebersihan, tata tertib bimbingan, serta kemandirian kelas (Ekuivalen 2 Jam Tatap Muka/Minggu).',
    duration: 0,
    timeRange: '',
    isActive: false,
    photos: [],
    photoCaptions: [],
  },
  {
    id: 'act5_c2',
    no: '17',
    component: '5. Melaksanakan Tugas Tambahan',
    activityName: 'Tugas Lainnya - Pembina Organisasi Siswa Intra Sekolah (OSIS) (Ekuivalen 2 Jam Tatap Muka/Minggu).',
    duration: 0,
    timeRange: '',
    isActive: false,
    photos: [],
    photoCaptions: [],
  },
  {
    id: 'act5_c3',
    no: '18',
    component: '5. Melaksanakan Tugas Tambahan',
    activityName: 'Tugas Lainnya - Pembina Ekstrakurikuler: Mengasuh rombongan belajar minat khusus, minimal 20 murid (Ekuivalen 2 Jam Tatap Muka/Minggu).',
    duration: 0,
    timeRange: '',
    isActive: false,
    photos: [],
    photoCaptions: [],
  },
  {
    id: 'act5_c4',
    no: '19',
    component: '5. Melaksanakan Tugas Tambahan',
    activityName: 'Tugas Lainnya - Koordinator Pengembangan Kompetensi Guru / Pendidik (Ekuivalen 2 Jam Tatap Muka/Minggu).',
    duration: 0,
    timeRange: '',
    isActive: false,
    photos: [],
    photoCaptions: [],
  },
  {
    id: 'act5_c5_1',
    no: '20',
    component: '5. Melaksanakan Tugas Tambahan',
    activityName: 'Tugas Lainnya - Pengurus Bursa Kerja Khusus (BKK) SMK: Ketua (Ekuivalen 2 Jam Tatap Muka/Minggu).',
    duration: 0,
    timeRange: '',
    isActive: false,
    photos: [],
    photoCaptions: [],
  },
  {
    id: 'act5_c5_2',
    no: '21',
    component: '5. Melaksanakan Tugas Tambahan',
    activityName: 'Tugas Lainnya - Pengurus Bursa Kerja Khusus (BKK) SMK: Personil Informasi Pasar Kerja / Hubungan Industri (Ekuivalen 1 Jam Tatap Muka/Minggu).',
    duration: 0,
    timeRange: '',
    isActive: false,
    photos: [],
    photoCaptions: [],
  },
  {
    id: 'act5_c6',
    no: '22',
    component: '5. Melaksanakan Tugas Tambahan',
    activityName: 'Tugas Lainnya - Guru Piket: Melaksanakan tugas piket minimal 1 hari per minggu, menjaga stabilitas dan keselamatan sekolah (Ekuivalen 1 Jam Tatap Muka/Minggu).',
    duration: 0,
    timeRange: '',
    isActive: false,
    photos: [],
    photoCaptions: [],
  },
  {
    id: 'act5_c7_1',
    no: '23',
    component: '5. Melaksanakan Tugas Tambahan',
    activityName: 'Tugas Lainnya - Pengurus Lembaga Sertifikasi Profesi (LSP) Pihak Pertama: Ketua (Ekuivalen 2 Jam Tatap Muka/Minggu).',
    duration: 0,
    timeRange: '',
    isActive: false,
    photos: [],
    photoCaptions: [],
  },
  {
    id: 'act5_c7_2',
    no: '24',
    component: '5. Melaksanakan Tugas Tambahan',
    activityName: 'Tugas Lainnya - Pengurus Lembaga Sertifikasi Profesi (LSP) Pihak Pertama: Kepala Bagian Sertifikasi / Mutu / Administrasi (Ekuivalen 1 Jam Tatap Muka/Minggu).',
    duration: 0,
    timeRange: '',
    isActive: false,
    photos: [],
    photoCaptions: [],
  },
  {
    id: 'act5_c8',
    no: '25',
    component: '5. Melaksanakan Tugas Tambahan',
    activityName: 'Tugas Lainnya - Koordinator Pengelolaan Kinerja Guru: Membantu kepala sekolah menyusun dan menelaah instrumen sasaran kinerja pegawai (Ekuivalen 2 Jam Tatap Muka/Minggu).',
    duration: 0,
    timeRange: '',
    isActive: false,
    photos: [],
    photoCaptions: [],
  },
  {
    id: 'act5_c9',
    no: '26',
    component: '5. Melaksanakan Tugas Tambahan',
    activityName: 'Tugas Lainnya - Koordinator Pembelajaran Berbasis Projek (P5): Mengkoordinasikan modul, tema, rekap nilai P5 (Ekuivalen 2 Jam Tatap Muka per Rombongan Belajar).',
    duration: 0,
    timeRange: '',
    isActive: false,
    photos: [],
    photoCaptions: [],
  },
  {
    id: 'act5_c10',
    no: '27',
    component: '5. Melaksanakan Tugas Tambahan',
    activityName: 'Tugas Lainnya - Koordinator Pembelajaran Pendidikan Inklusi: Melaksanakan sinkronisasi sistem bagi anak berkebutuhan khusus (Ekuivalen 2 Jam Tatap Muka/Minggu).',
    duration: 0,
    timeRange: '',
    isActive: false,
    photos: [],
    photoCaptions: [],
  },
  {
    id: 'act5_c11_1',
    no: '28',
    component: '5. Melaksanakan Tugas Tambahan',
    activityName: 'Tugas Lainnya - Tim Pencegahan dan Penanganan Kekerasan (TPPK) / Satgas Perlindungan: Koordinator Tim (Ekuivalen 2 Jam Tatap Muka/Minggu).',
    duration: 0,
    timeRange: '',
    isActive: false,
    photos: [],
    photoCaptions: [],
  },
  {
    id: 'act5_c11_2',
    no: '29',
    component: '5. Melaksanakan Tugas Tambahan',
    activityName: 'Tugas Lainnya - Tim Pencegahan dan Penanganan Kekerasan (TPPK) / Satgas Perlindungan: Anggota Tim (Ekuivalen 1 Jam Tatap Muka/Minggu).',
    duration: 0,
    timeRange: '',
    isActive: false,
    photos: [],
    photoCaptions: [],
  },
  {
    id: 'act5_c12',
    no: '30',
    component: '5. Melaksanakan Tugas Tambahan',
    activityName: 'Tugas Lainnya - Pengurus Kepanitiaan Acara di Satuan Pendidikan (Ketua/Sekretaris/Bendahara), minimal 1 bulan kerja (Ekuivalen 1 Jam Tatap Muka/Minggu).',
    duration: 0,
    timeRange: '',
    isActive: false,
    photos: [],
    photoCaptions: [],
  },
  {
    id: 'act5_c13_1',
    no: '31',
    component: '5. Melaksanakan Tugas Tambahan',
    activityName: 'Tugas Lainnya - Pengurus Organisasi Bidang Pendidikan Resmi tingkat Nasional (Ekuivalen 3 Jam Tatap Muka/Minggu).',
    duration: 0,
    timeRange: '',
    isActive: false,
    photos: [],
    photoCaptions: [],
  },
  {
    id: 'act5_c13_2',
    no: '32',
    component: '5. Melaksanakan Tugas Tambahan',
    activityName: 'Tugas Lainnya - Pengurus Organisasi Bidang Pendidikan Resmi tingkat Provinsi (Ekuivalen 2 Jam Tatap Muka/Minggu).',
    duration: 0,
    timeRange: '',
    isActive: false,
    photos: [],
    photoCaptions: [],
  },
  {
    id: 'act5_c13_3',
    no: '33',
    component: '5. Melaksanakan Tugas Tambahan',
    activityName: 'Tugas Lainnya - Pengurus Organisasi Bidang Pendidikan Resmi tingkat Kabupaten / Kota / Gugus (Ekuivalen 1 Jam Tatap Muka/Minggu).',
    duration: 0,
    timeRange: '',
    isActive: false,
    photos: [],
    photoCaptions: [],
  },
  {
    id: 'act5_c14',
    no: '34',
    component: '5. Melaksanakan Tugas Tambahan',
    activityName: 'Tugas Lainnya - Tutor Resmi pada Pendidikan Kesetaraan Paket A/B/C (Ekuivalen Maksimal 6 Jam Tatap Muka dengan Rasio 1:1).',
    duration: 0,
    timeRange: '',
    isActive: false,
    photos: [],
    photoCaptions: [],
  },
  {
    id: 'act5_c15',
    no: '35',
    component: '5. Melaksanakan Tugas Tambahan',
    activityName: 'Tugas Lainnya - Instruktur / Narasumber / Fasilitator berlisensi pada Program Pengembangan Kompetensi Resmi (Ekuivalen 1 Jam Tatap Muka/Minggu).',
    duration: 0,
    timeRange: '',
    isActive: false,
    photos: [],
    photoCaptions: [],
  },
  {
    id: 'act5_c16',
    no: '36',
    component: '5. Melaksanakan Tugas Tambahan',
    activityName: 'Tugas Lainnya - Peserta pada Program Pengembangan Kompetensi terstruktur lembaga pelatih (Ekuivalen 1 Jam Tatap Muka/Minggu).',
    duration: 0,
    timeRange: '',
    isActive: false,
    photos: [],
    photoCaptions: [],
  },
  {
    id: 'act5_c17',
    no: '37',
    component: '5. Melaksanakan Tugas Tambahan',
    activityName: 'Tugas Lainnya - Koordinator Kelompok Kerja Guru (KKG) / Musyawarah Guru Mata Pelajaran (MGMP) / Gugus (Ekuivalen 1 Jam Tatap Muka/Minggu).',
    duration: 0,
    timeRange: '',
    isActive: false,
    photos: [],
    photoCaptions: [],
  },
  {
    id: 'act5_c18',
    no: '38',
    component: '5. Melaksanakan Tugas Tambahan',
    activityName: 'Tugas Lainnya - Pengurus Organisasi Kemasyarakatan Nonpolitik tingkat Kabupaten / Provinsi / Pusat (Ekuivalen 1 Jam Tatap Muka/Minggu).',
    duration: 0,
    timeRange: '',
    isActive: false,
    photos: [],
    photoCaptions: [],
  },
  {
    id: 'act5_c19',
    no: '39',
    component: '5. Melaksanakan Tugas Tambahan',
    activityName: 'Tugas Lainnya - Pengurus Organisasi Pemerintahan Nonstruktural bentukan kementerian / dinas (Ekuivalen 1 Jam Tatap Muka/Minggu).',
    duration: 0,
    timeRange: '',
    isActive: false,
    photos: [],
    photoCaptions: [],
  },
];

export interface TeacherData {
  nama: string;
  nuptk: string;
  nip: string;
  tugasTambahan?: string;
}

export const SMAN_3_BOMBANA_TEACHERS: TeacherData[] = [
  { nama: "A. Hamriana Rapik", nuptk: "7754763664300102", nip: "198504222009032007", tugasTambahan: "Guru Piket" },
  { nama: "Agus Nada", nuptk: "9563744647200363", nip: "196612311992031095", tugasTambahan: "Kepala Laboratorium" },
  { nama: "Arfani", nuptk: "6563747650300453", nip: "196912312006041102", tugasTambahan: "Guru Piket" },
  { nama: "Aryanto", nuptk: "7536762663200013", nip: "198412042022211010", tugasTambahan: "Guru Wali" },
  { nama: "Asban", nuptk: "1949758661200022", nip: "198006172006041019", tugasTambahan: "Wakil Kepala Sekolah Humas" },
  { nama: "Asis Lawa", nuptk: "0144756659200013", nip: "197808122010011019", tugasTambahan: "Wakil Kepala Sekolah Kesiswaan" },
  { nama: "Bahrudin", nuptk: "3933764666120002", nip: "198606012023211011", tugasTambahan: "Guru Wali" },
  { nama: "Dahlia Tangka", nuptk: "5348760661300023", nip: "198210162008042002", tugasTambahan: "Guru Wali" },
  { nama: "DARMAWATI", nuptk: "2535780681230013", nip: "-", tugasTambahan: "Guru Wali" },
  { nama: "DEWI FATMAWATI", nuptk: "5542776677230093", nip: "199812102024212016", tugasTambahan: "Guru Wali" },
  { nama: "DIAN ADELIA DINATA", nuptk: "8035777678230093", nip: "199907032024212028", tugasTambahan: "Guru Wali" },
  { nama: "EMINARTI", nuptk: "0155775676230053", nip: "199708232024212027", tugasTambahan: "Guru Wali" },
  { nama: "ERJIANSYAH", nuptk: "6954780681130012", nip: "-", tugasTambahan: "Guru Wali" },
  { nama: "FEBY FRISKA PURNAMA", nuptk: "7558780681230002", nip: "200202262024212001", tugasTambahan: "Guru Wali" },
  { nama: "Feri Angriawan", nuptk: "1050765667120003", nip: "198707182011011009", tugasTambahan: "Guru Wali" },
  { nama: "Fitrawan", nuptk: "0556778679130032", nip: "-", tugasTambahan: "Guru Wali" },
  { nama: "Fitriani", nuptk: "4144770671130043", nip: "199208122022212008", tugasTambahan: "Guru Piket" },
  { nama: "Hartati", nuptk: "1942756657300042", nip: "197806102011012008", tugasTambahan: "Guru Wali" },
  { nama: "Hasmawati Harfin", nuptk: "1463761661220002", nip: "198301312008032002", tugasTambahan: "Guru Wali" },
  { nama: "Hawa Safitri", nuptk: "7553778679230053", nip: "-", tugasTambahan: "Guru Wali" },
  { nama: "IHDINA FAUZIA RAHMI. A", nuptk: "3434778679230112", nip: "-", tugasTambahan: "Guru Wali" },
  { nama: "IKMAL", nuptk: "0041777678130163", nip: "-", tugasTambahan: "Guru Wali" },
  { nama: "IRA RISWANA", nuptk: "4042780681230013", nip: "-", tugasTambahan: "Guru Wali" },
  { nama: "Jumriani Hatta", nuptk: "0145755657300033", nip: "197708132014102001", tugasTambahan: "Guru Piket" },
  { nama: "Karaeng Nur Riskillah", nuptk: "8542771672130042", nip: "199302102023212030", tugasTambahan: "Guru Wali" },
  { nama: "LISDAYANTI", nuptk: "6534774675230093", nip: "199612022025212065", tugasTambahan: "Guru Wali" },
  { nama: "Makmur", nuptk: "0444746647200012", nip: "196801122005021003", tugasTambahan: "Wali kelas" },
  { nama: "Martini Muslimin", nuptk: "3439755657300012", nip: "197701072005022002", tugasTambahan: "Wakil Kepala Sekolah Kurikulum" },
  { nama: "Marwati", nuptk: "8547753656300002", nip: "197502152022212002", tugasTambahan: "Guru Wali" },
  { nama: "Masyrikin", nuptk: "2939747650200032", nip: "196906072006041013", tugasTambahan: "Guru Piket" },
  { nama: "Meriyanto Randa", nuptk: "2649752653200012", nip: "197403172005022007", tugasTambahan: "Kepala Perpustakaan" },
  { nama: "MUHAMMAD IKBAL", nuptk: "3434778679130052", nip: "-", tugasTambahan: "Guru Wali" },
  { nama: "Muhibudin", nuptk: "4834762663200042", nip: "198405022010011021", tugasTambahan: "Guru Wali" },
  { nama: "Nama Mardiana", nuptk: "4333775676230173", nip: "-", tugasTambahan: "Guru Wali" },
  { nama: "NOLA OKTA VILIA. N", nuptk: "2544778679230033", nip: "200012122024212005", tugasTambahan: "Guru Wali" },
  { nama: "Nurhikmah", nuptk: "8545755657300023", nip: "197712132006042011", tugasTambahan: "Guru Wali" },
  { nama: "Nuriani", nuptk: "2261763664230243", nip: "198509292024212025", tugasTambahan: "Guru Wali" },
  { nama: "Putri Reski Adnan", nuptk: "-", nip: "-", tugasTambahan: "Guru Wali" },
  { nama: "Rahayana Djaila", nuptk: "3054753654220003", nip: "197507222010012006", tugasTambahan: "Guru Wali" },
  { nama: "Rahmawati A", nuptk: "9563759660300053", nip: "197805232005022003", tugasTambahan: "Guru Piket" },
  { nama: "Rasidin", nuptk: "2741749654200002", nip: "197104092010011005", tugasTambahan: "Guru Wali" },
  { nama: "RUKMANA PANAUNGI", nuptk: "8534779680230023", nip: "-", tugasTambahan: "Guru Wali" },
  { nama: "Safaria", nuptk: "0035768669130123", nip: "199007032023212036", tugasTambahan: "Guru Piket" },
  { nama: "Samsidar", nuptk: "8049759660300043", nip: "198107172006042042", tugasTambahan: "Guru Piket" },
  { nama: "Sinarni", nuptk: "4843744645300002", nip: "196605112005022001", tugasTambahan: "Guru Piket" },
  { nama: "Siska Damayanti Syukur", nuptk: "0949775676230052", nip: "199706172023212016", tugasTambahan: "Guru Wali" },
  { nama: "Sitti Hardinati", nuptk: "6245762663200023", nip: "198409132009032003", tugasTambahan: "Guru Wali" },
  { nama: "ST. INAYA FAHMI", nuptk: "2455778679230023", nip: "-", tugasTambahan: "Guru Wali" },
  { nama: "SUCI REGA YASA", nuptk: "5461775676230162", nip: "199701292025212120", tugasTambahan: "Guru Wali" },
  { nama: "Sumarni", nuptk: "9446761664300003", nip: "198311142009032007", tugasTambahan: "Guru Wali" },
  { nama: "TRI FAISAL. F.A", nuptk: "1538776677130192", nip: "-", tugasTambahan: "Guru Wali" },
  { nama: "ULFAYANTI", nuptk: "-", nip: "-", tugasTambahan: "Guru Wali" },
  { nama: "Ummy Kalsum", nuptk: "9152747650300043", nip: "196908202007012020", tugasTambahan: "Guru Wali" },
  { nama: "Wahyuni Pua Aru", nuptk: "2352764665220003", nip: "198610202010012026", tugasTambahan: "Pembina Pramuka" },
  { nama: "Yahya", nuptk: "3955756660200002", nip: "197806232006041006", tugasTambahan: "Guru Wali" },
  { nama: "Yasniarsih", nuptk: "4743745647300032", nip: "196704112005022002", tugasTambahan: "Wakil Kepala Sekolah Sarpras" },
  { nama: "YESSI PASKA LINA", nuptk: "7737776677230202", nip: "-", tugasTambahan: "Guru Wali" },
  { nama: "Yunus", nuptk: "1563747648200113", nip: "196912312005011091", tugasTambahan: "Guru Wali" },
  { nama: "YUSNIDAR", nuptk: "1634773674130032", nip: "199503022024212040", tugasTambahan: "Guru Wali" },
  { nama: "Yuyun Sulistianti", nuptk: "6436775676230062", nip: "199701042024212028", tugasTambahan: "Guru Wali" }
];
